// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfqwvl3qCNNFLPXmT1KIYbUz4Go7lNaZo',
    appId: '1:437797167182:web:3a469ba293035e0bd9231f',
    messagingSenderId: '437797167182',
    projectId: 'flutter-training-97807',
    authDomain: 'flutter-training-97807.firebaseapp.com',
    storageBucket: 'flutter-training-97807.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXzZTKPdieVlXSJ0DskofkxS9IM2EQD0Y',
    appId: '1:437797167182:android:f52581670445306ed9231f',
    messagingSenderId: '437797167182',
    projectId: 'flutter-training-97807',
    storageBucket: 'flutter-training-97807.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnatLt88ipDXrY6xxgC2XTB5hDlKr-DXQ',
    appId: '1:437797167182:ios:832511575d6c16e5d9231f',
    messagingSenderId: '437797167182',
    projectId: 'flutter-training-97807',
    storageBucket: 'flutter-training-97807.appspot.com',
    iosBundleId: 'com.example.testTechniqueInventivIt',
  );
}
